module.exports = Object.freeze({
  CONSIGNMENT_LEAVE: 'consignment-leave',
  CONSIGNMENT_LEAVE_LABEL: 'Did the consignment leave the UK?',
  MEANS_OF_TRANSPORT: 'transport-type',
  MEANS_OF_TRANSPORT_LABEL: 'Means of transport',
  IDENTIFICATION: 'identification',
  IDENTIFICATION_LABEL: 'Identification',
  DOCUMENTATION: 'documentation',
  DOCUMENTATION_LABEL: 'Documentation',
  DEPARTURE_DATE: 'leave-date',
  DEPARTURE_DATE_LABEL: 'Departure date',
  DEPARTURE_DATE_DAY: 'leave-date-day',
  DEPARTURE_DATE_DAY_LABEL: 'Day of departure',
  DEPARTURE_DATE_MONTH: 'leave-date-month',
  DEPARTURE_DATE_MONTH_LABEL: 'Month of departure',
  DEPARTURE_DATE_YEAR: 'leave-date-year',
  DEPARTURE_DATE_YEAR_LABEL: 'Year of departure',
  EXIT_BIP: 'exitBIP',
  EXIT_BIP_LABEL: 'Exit BIP/DPE',
  DESTINATION_COUNTRY: 'redispatching-country',
  DESTINATION_COUNTRY_LABEL: 'Destination country',
  CONTROLLED_DESTINATION_REACHED: 'consignment-arrival',
  CONTROLLED_DESTINATION_REACHED_LABEL: 'Did the consignment reach the controlled destination?',
  CONTROLLED_DESTINATION_NOT_REACHED_REASON: 'consignment-no-arrival-reason',
  CONTROLLED_DESTINATION_NOT_REACHED_REASON_LABEL: 'Reason',
  DESTRUCTION_DATE: 'destruction-date',
  DESTRUCTION_DATE_LABEL: 'Destruction date',
  DESTRUCTION_DATE_DAY: 'destruction-date-day',
  DESTRUCTION_DATE_DAY_LABEL: 'Day of consignment destruction',
  DESTRUCTION_DATE_MONTH: 'destruction-date-month',
  DESTRUCTION_DATE_MONTH_LABEL: 'Month of consignment destruction',
  DESTRUCTION_DATE_YEAR: 'destruction-date-year',
  DESTRUCTION_DATE_YEAR_LABEL: 'Year of consignment destruction',
  ETAG: 'etag',
  CONSIGNMENT_LEAVE_OPTIONS: {
    YES: 'yes',
    NO: 'no',
    DESTRUCTION: 'destruction'
  },
  CONSIGNMENT_ARRIVAL_OPTIONS: {
    YES: 'Yes',
    NO: 'No'
  },
  SEARCH_STRING_KEY: 'search-string',
  SEARCH_STRING_LABEL: 'Search',
  CONSIGNEE_STRING_KEY: 'consignee-string',
  CONSIGNEE_STRING_LABEL: 'Consignee',
  START_DATE_DAY_KEY: 'start-date-day',
  START_DATE_DAY_LABEL: 'Start Date Day',
  START_DATE_MONTH_KEY: 'start-date-month',
  START_DATE_MONTH_LABEL: 'Start Date Month',
  START_DATE_YEAR_KEY: 'start-date-year',
  START_DATE_YEAR_LABEL: 'Start Date Year',
  START_DATE_KEY: 'start-date',
  START_DATE_LABEL: 'Start Date',
  END_DATE_DAY_KEY: 'end-date-day',
  END_DATE_DAY_LABEL: 'End Date Day',
  END_DATE_MONTH_KEY: 'end-date-month',
  END_DATE_MONTH_LABEL: 'End Date Month',
  END_DATE_YEAR_KEY: 'end-date-year',
  END_DATE_YEAR_LABEL: 'End Date Year',
  END_DATE_KEY: 'end-date',
  END_DATE_LABEL: 'End Date',
  SELECTED_BIP_KEY: 'selectedBIP',
  SELECTED_STATUS_KEY: 'selectedStatus',
  SELECTED_CONTROL_STATUS_KEY: 'selectedControlStatus',
  COUNTRY_OF_ORIGIN_KEY: 'countryOfOrigin',
  DATE_RANGE_KEY: 'dateRange',
  SELECTED_CERTIFICATE_TYPE_KEY: 'selectedCertificateType',
  DECISION_KEY: 'selectedDecision'
})
